version: "3.7"

services:
  wuzapi-server:
    image: ghcr.io/buildzero-program/wuzapi:${IMAGE_TAG:-latest}
    networks:
      - network_public
    environment:
      - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN}
      - DB_USER=${DB_USER:-wuzapi}
      - DB_PASSWORD=${DB_PASSWORD:-wuzapi}
      - DB_NAME=${DB_NAME:-wuzapi}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - TZ=${TZ:-America/Sao_Paulo}
      - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
      - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-WuzAPI}
      # RabbitMQ configuration Optional
      - RABBITMQ_URL=amqp://wuzapi:wuzapi@rabbitmq:5672/
      - RABBITMQ_QUEUE=whatsapp_events
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      labels:
        - traefik.enable=true
        - traefik.http.routers.wuzapi-server.rule=Host(`wuzapi.buildzero.ai`)
        - traefik.http.routers.wuzapi-server.entrypoints=websecure
        - traefik.http.routers.wuzapi-server.priority=1
        - traefik.http.routers.wuzapi-server.tls.certresolver=letsencryptresolver
        - traefik.http.routers.wuzapi-server.service=wuzapi-server
        - traefik.http.services.wuzapi-server.loadbalancer.server.port=${WUZAPI_PORT:-8080}
    volumes:
      - wuzapi_data:/app/data

  # RabbitMQ service OPTIONAL
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - network_public
    environment:
      - RABBITMQ_DEFAULT_USER=wuzapi
      - RABBITMQ_DEFAULT_PASS=wuzapi
      - RABBITMQ_DEFAULT_VHOST=/
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.5"
          memory: 256MB
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  wuzapi_data:
  rabbitmq_data:

networks:
  network_public:
    name: network_public
    external: true
