version: "3.7"
services:

## --------------------------- WUZAPI SERVICE --------------------------- ##

  wuzapi:
    image: ghcr.io/buildzero-program/wuzapi:${IMAGE_TAG:-latest}

    networks:
      - network

    environment:
      ## WuzAPI Configuration
      - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN}
      - WUZAPI_PORT=8080

      ## Database (Neon PostgreSQL)
      - DB_USER=${DB_USER:-wuzapi}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-wuzapi}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_SSLMODE=require

      ## Webhook
      - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
      - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-WuzAPI}

      ## Timezone
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.wuzapi.rule=Host(`wpp.buildzero.ai`)
        - traefik.http.services.wuzapi.loadbalancer.server.port=8080
        - traefik.http.routers.wuzapi.service=wuzapi
        - traefik.http.routers.wuzapi.tls.certresolver=letsencryptresolver
        - traefik.http.routers.wuzapi.entrypoints=websecure
        - traefik.http.routers.wuzapi.tls=true

    volumes:
      - wuzapi_data:/app/dbdata

## --------------------------- WUZAPI SERVICE --------------------------- ##

volumes:
  wuzapi_data:

networks:
  network:
    name: network
    external: true
